 insert into sport (label) values ('Accrobranche') on conflict do nothing;
 insert into sport (label) values ('Acrosport') on conflict do nothing;
 insert into sport (label) values ('Aérobic') on conflict do nothing;
 insert into sport (label) values ('Archerie') on conflict do nothing;
 insert into sport (label) values ('Aïkido') on conflict do nothing;
 insert into sport (label) values ('Airsoft') on conflict do nothing;
 insert into sport (label) values ('Alpinisme') on conflict do nothing;
 insert into sport (label) values ('Aquabiking') on conflict do nothing;
 insert into sport (label) values ('Aquagym') on conflict do nothing;
 insert into sport (label) values ('Athlétisme') on conflict do nothing;
 insert into sport (label) values ('Automobile') on conflict do nothing;
 insert into sport (label) values ('Aviation') on conflict do nothing;
 insert into sport (label) values ('Aviron') on conflict do nothing;
 insert into sport (label) values ('Arts Martiaux') on conflict do nothing;
 insert into sport (label) values ('Baby-foot') on conflict do nothing;
 insert into sport (label) values ('Badminton') on conflict do nothing;
 insert into sport (label) values ('Base-jump') on conflict do nothing;
 insert into sport (label) values ('Baseball') on conflict do nothing;
 insert into sport (label) values ('Basket-ball') on conflict do nothing;
 insert into sport (label) values ('Biathlon') on conflict do nothing;
 insert into sport (label) values ('Billard') on conflict do nothing;
 insert into sport (label) values ('Bike and Run') on conflict do nothing;
 insert into sport (label) values ('BMX') on conflict do nothing;
 insert into sport (label) values ('Boardercross') on conflict do nothing;
 insert into sport (label) values ('Bobsleigh') on conflict do nothing;
 insert into sport (label) values ('Boomerang') on conflict do nothing;
 insert into sport (label) values ('Bowling') on conflict do nothing;
 insert into sport (label) values ('Boxe') on conflict do nothing;
 insert into sport (label) values ('Bras de fer') on conflict do nothing;
 insert into sport (label) values ('Beach Volley') on conflict do nothing;
 insert into sport (label) values ('Canoë') on conflict do nothing;
 insert into sport (label) values ('Canoë-kayak') on conflict do nothing;
 insert into sport (label) values ('Canyoning') on conflict do nothing;
 insert into sport (label) values ('Capoeira') on conflict do nothing;
 insert into sport (label) values ('Catch') on conflict do nothing;
 insert into sport (label) values ('Cheerleading') on conflict do nothing;
 insert into sport (label) values ('course automobile') on conflict do nothing;
 insert into sport (label) values ('Course à pied') on conflict do nothing;
 insert into sport (label) values ('Cricket') on conflict do nothing;
 insert into sport (label) values ('Cross (équitation)') on conflict do nothing;
 insert into sport (label) values ('Cross-country') on conflict do nothing;
 insert into sport (label) values ('Cross triathlon') on conflict do nothing;
 insert into sport (label) values ('CrossFit') on conflict do nothing;
 insert into sport (label) values ('Culturisme') on conflict do nothing;
 insert into sport (label) values ('Curling') on conflict do nothing;
 insert into sport (label) values ('Cyclisme') on conflict do nothing;
 insert into sport (label) values ('Cyclo-cross') on conflict do nothing;
 insert into sport (label) values ('Danse sportive') on conflict do nothing;
 insert into sport (label) values ('Décathlon') on conflict do nothing;
 insert into sport (label) values ('Deltaplane') on conflict do nothing;
 insert into sport (label) values ('Duathlon') on conflict do nothing;
 insert into sport (label) values ('Dodgeball') on conflict do nothing;
 insert into sport (label) values ('Double Dutch') on conflict do nothing;
 insert into sport (label) values ('Équitation') on conflict do nothing;
 insert into sport (label) values ('Escalade') on conflict do nothing;
 insert into sport (label) values ('Escrime') on conflict do nothing;
 insert into sport (label) values ('Football') on conflict do nothing;
 insert into sport (label) values ('Football américain') on conflict do nothing;
 insert into sport (label) values ('Footing') on conflict do nothing;
 insert into sport (label) values ('Futsal') on conflict do nothing;
 insert into sport (label) values ('Glisse') on conflict do nothing;
 insert into sport (label) values ('Golf') on conflict do nothing;
 insert into sport (label) values ('Gymnastique') on conflict do nothing;
 insert into sport (label) values ('Gymnastique rythmique') on conflict do nothing;
 insert into sport (label) values ('Haltérophilie') on conflict do nothing;
 insert into sport (label) values ('Handball') on conflict do nothing;
 insert into sport (label) values ('Hockey') on conflict do nothing;
 insert into sport (label) values ('Hockey subaquatique') on conflict do nothing;
 insert into sport (label) values ('Hockey sur gazon') on conflict do nothing;
 insert into sport (label) values ('Hockey sur glace') on conflict do nothing;
 insert into sport (label) values ('Horse-ball') on conflict do nothing;
 insert into sport (label) values ('hip Hop') on conflict do nothing;
 insert into sport (label) values ('Judo') on conflict do nothing;
 insert into sport (label) values ('Jet ski') on conflict do nothing;
 insert into sport (label) values ('Karaté') on conflict do nothing;
 insert into sport (label) values ('Karting') on conflict do nothing;
 insert into sport (label) values ('Kayak') on conflict do nothing;
 insert into sport (label) values ('Kick-boxing') on conflict do nothing;
 insert into sport (label) values ('Kitesurfing') on conflict do nothing;
 insert into sport (label) values ('Kung fu') on conflict do nothing;
 insert into sport (label) values ('Lancer de disque') on conflict do nothing;
 insert into sport (label) values ('Lancer de javelot') on conflict do nothing;
 insert into sport (label) values ('Lancer de marteau') on conflict do nothing;
 insert into sport (label) values ('Lancer de poids') on conflict do nothing;
 insert into sport (label) values ('Luge de course') on conflict do nothing;
 insert into sport (label) values ('Lutte') on conflict do nothing;
 insert into sport (label) values ('Marche') on conflict do nothing;
 insert into sport (label) values ('Marche nordique') on conflict do nothing;
 insert into sport (label) values ('Motomarine') on conflict do nothing;
 insert into sport (label) values ('Motoneige') on conflict do nothing;
 insert into sport (label) values ('Musculation') on conflict do nothing;
 insert into sport (label) values ('Marathon') on conflict do nothing;
 insert into sport (label) values ('MMA') on conflict do nothing;
 insert into sport (label) values ('Natation') on conflict do nothing;
 insert into sport (label) values ('Natation synchronisée') on conflict do nothing;
 insert into sport (label) values ('Nautisme') on conflict do nothing;
 insert into sport (label) values ('Orientation') on conflict do nothing;
 insert into sport (label) values ('Paddle') on conflict do nothing;
 insert into sport (label) values ('Padel') on conflict do nothing;
 insert into sport (label) values ('Paintball') on conflict do nothing;
 insert into sport (label) values ('Parachutisme') on conflict do nothing;
 insert into sport (label) values ('Parapente') on conflict do nothing;
 insert into sport (label) values ('Parkour') on conflict do nothing;
 insert into sport (label) values ('Patinage') on conflict do nothing;
 insert into sport (label) values ('Patinage artistique') on conflict do nothing;
 insert into sport (label) values ('Patinage de vitesse') on conflict do nothing;
 insert into sport (label) values ('Patinage synchronisé') on conflict do nothing;
 insert into sport (label) values ('Pêche sportive') on conflict do nothing;
 insert into sport (label) values ('Pentathlon') on conflict do nothing;
 insert into sport (label) values ('Pétanque') on conflict do nothing;
 insert into sport (label) values ('Planche à voile') on conflict do nothing;
 insert into sport (label) values ('Planeur') on conflict do nothing;
 insert into sport (label) values ('Plongée') on conflict do nothing;
 insert into sport (label) values ('Plongeon') on conflict do nothing;
 insert into sport (label) values ('Quad') on conflict do nothing;
 insert into sport (label) values ('Rafting') on conflict do nothing;
 insert into sport (label) values ('Rallye automobile') on conflict do nothing;
 insert into sport (label) values ('Raquette à neige') on conflict do nothing;
 insert into sport (label) values ('Roller') on conflict do nothing;
 insert into sport (label) values ('Rugby') on conflict do nothing;
 insert into sport (label) values ('Saut à la perche') on conflict do nothing;
 insert into sport (label) values ('Saut à ski') on conflict do nothing;
 insert into sport (label) values ('Saut en hauteur') on conflict do nothing;
 insert into sport (label) values ('Saut en longueur') on conflict do nothing;
 insert into sport (label) values ('Skateboard') on conflict do nothing;
 insert into sport (label) values ('Skater hockey') on conflict do nothing;
 insert into sport (label) values ('Skeleton') on conflict do nothing;
 insert into sport (label) values ('Ski') on conflict do nothing;
 insert into sport (label) values ('Snowboard') on conflict do nothing;
 insert into sport (label) values ('Snowskate') on conflict do nothing;
 insert into sport (label) values ('Spéléologie') on conflict do nothing;
 insert into sport (label) values ('Squash') on conflict do nothing;
 insert into sport (label) values ('Step') on conflict do nothing;
 insert into sport (label) values ('Sumo') on conflict do nothing;
 insert into sport (label) values ('Surf') on conflict do nothing;
 insert into sport (label) values ('Samba') on conflict do nothing;
 insert into sport (label) values ('Taekwondo') on conflict do nothing;
 insert into sport (label) values ('Tango') on conflict do nothing;
 insert into sport (label) values ('Tennis') on conflict do nothing;
 insert into sport (label) values ('Tennis de table') on conflict do nothing;
 insert into sport (label) values ('Tir sportif') on conflict do nothing;
 insert into sport (label) values ('Trampoline') on conflict do nothing;
 insert into sport (label) values ('Triathlon') on conflict do nothing;
 insert into sport (label) values ('Tricking') on conflict do nothing;
 insert into sport (label) values ('Triple saut') on conflict do nothing;
 insert into sport (label) values ('Trottinette freestyle') on conflict do nothing;
 insert into sport (label) values ('Twirling') on conflict do nothing;
 insert into sport (label) values ('Ultimate') on conflict do nothing;
 insert into sport (label) values ('Vélocross') on conflict do nothing;
 insert into sport (label) values ('Voile') on conflict do nothing;
 insert into sport (label) values ('Volley-ball') on conflict do nothing;
 insert into sport (label) values ('Voltige aérienne') on conflict do nothing;
 insert into sport (label) values ('Voltige') on conflict do nothing;
 insert into sport (label) values ('Wakeboard') on conflict do nothing;
 insert into sport (label) values ('Water-polo') on conflict do nothing;
 insert into sport (label) values ('Waveboard') on conflict do nothing;
 insert into sport (label) values ('Yoga') on conflict do nothing;
 insert into sport (label) values ('Zumba') on conflict do nothing;
 
INSERT INTO utilisateur (date_naissance, email, nom, "password", prenom, username) VALUES('1998-02-20', 'quentindamman59@gmail.com', 'DAMMAN', '$2a$10$kBOX9eshjvXiGQnLhzWeReCuru7m3PdoK9B4cnuxJ.DxzI2p9Z/R6', 'Quentin', 'QUENTINOS') on conflict do nothing;
INSERT INTO utilisateur (date_naissance, email, nom, "password", prenom, username) VALUES('1998-02-20', 'psackebandt@outlook.fr', 'SACKEBANDT', '$2a$10$kBOX9eshjvXiGQnLhzWeReCuru7m3PdoK9B4cnuxJ.DxzI2p9Z/R6', 'Paul', 'PAULO') on conflict do nothing;
INSERT INTO utilisateur (date_naissance, email, nom, "password", prenom, username) VALUES('1998-02-20', 'mtosaba@gmail.com', 'SABA', '$2a$10$kBOX9eshjvXiGQnLhzWeReCuru7m3PdoK9B4cnuxJ.DxzI2p9Z/R6', 'Matéo', 'MATEO') on conflict do nothing;
INSERT INTO utilisateur (date_naissance, email, nom, "password", prenom, username) VALUES('1998-02-20', 'h.bogrand@gmail.com', 'BOGRAND', '$2a$10$S3CANLJ6NBlsVw5mJqo.cOz2QQOjksENbB42nK6peFz7cpWEgiwCa', 'Hugo', 'hugh59') on conflict do nothing;

insert into journal (id_utilisateur) values (4);

insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2020-12-19', 4, 'On a bien ris', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2020-12-20', 4, 'Toujours aussi drôle', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-01-05', 2, 'ça ira mieux', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-01-07', 2, 'peux mieux faire', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-02-10', 3, 'soulagé !', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-02-11', 3, 'quel amusement', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-03-07', 4, 'super temps', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-03-13', 4, 'Je suis chanceux', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-04', 1, 'deepWork compliqué', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-09', 1, 'objectif raté !', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-15', 3, 'En sourire !', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-16', 3, 'belle journée', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-17', 2, 'du nimporte quoi !!', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-18', 1, 'tout est vainc', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-18', 1, 'flop journée !', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-24', 4, 'objectif accompli', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-04-24', 4, 'Je suis redevable', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-05-15', 3, 'En sourire !', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-05-16', 3, 'surprenante journée', 'blablabla', 1);
insert into Jour (date_jour, humeur, titre, texte, id_journal) values ('2021-05-17', 2, 'pourquoi maintenant ?!', 'blablabla', 1);





